apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage.fullname" . }}-backstage
  labels:
  {{- include "backstage.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backstage.type }}
  selector:
    app: backstage
  {{- include "backstage.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.backstage.ports | toYaml | nindent 2 }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "backstage.fullname" . }}-backstage
  labels:
  {{- include "backstage.labels" . | nindent 4 }}
spec:
  gateways:
  - backstage-gateway
  hosts:
  - backstage.sevira.cloud
  http:
  - route:
    - destination:
        host: backstage.backstage.svc.cluster.local
        port:
          number: 80
      weight: 100