apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "backstage.fullname" . }}-cluster-ro
  labels:
  {{- include "backstage.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:aggregate-to-view
subjects:
- kind: ServiceAccount
  name: '{{ include "backstage.fullname" . }}-service-account'
  namespace: '{{ .Release.Namespace }}'