apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backstage.fullname" . }}-backstage
  labels:
  {{- include "backstage.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backstage.replicas }}
  selector:
    matchLabels:
      app: backstage
    {{- include "backstage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: backstage
      {{- include "backstage.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: POSTGRES_PORT
          value: {{ quote .Values.backstage.backstage.env.postgresPort }}
        - name: POSTGRES_HOST
          value: {{ quote .Values.backstage.backstage.env.postgresHost }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - secretRef:
            name: postgres-secrets
        - secretRef:
            name: backstage-secrets
        - secretRef:
            name: github-auth-secrets
        - secretRef:
            name: eks-secrets
        image: {{ .Values.backstage.backstage.image.repository }}:{{ .Values.backstage.backstage.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.backstage.backstage.imagePullPolicy }}
        name: backstage
        ports:
        - containerPort: 7007
          name: http
        resources: {}
      serviceAccountName: {{ include "backstage.fullname" . }}-service-account