apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "backstage.fullname" . }}-gateway
  labels:
  {{- include "backstage.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - backstage.sevira.cloud
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - backstage.sevira.cloud
    port:
      name: https-workloads
      number: 443
      protocol: HTTP
    tls:
      mode: PASSTHROUGH