apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backstage.fullname" . }}-service-account
  labels:
  {{- include "backstage.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.serviceAccount.annotations | nindent 4 }}